407b97dc98e0
*** Found local files:
***   * /opt/airflow/logs/dag_id=dag_spark_daily/run_id=manual__2025-04-13T04:15:14.218770+00:00/task_id=spark_cleaning_job/attempt=1.log
[2025-04-13, 13:15:16 KST] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_spark_daily.spark_cleaning_job manual__2025-04-13T04:15:14.218770+00:00 [queued]>
[2025-04-13, 13:15:16 KST] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_spark_daily.spark_cleaning_job manual__2025-04-13T04:15:14.218770+00:00 [queued]>
[2025-04-13, 13:15:16 KST] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-04-13, 13:15:16 KST] {taskinstance.py:1382} INFO - Executing <Task(SparkSubmitOperator): spark_cleaning_job> on 2025-04-13 04:15:14.218770+00:00
[2025-04-13, 13:15:16 KST] {standard_task_runner.py:57} INFO - Started process 870 to run task
[2025-04-13, 13:15:16 KST] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_spark_daily', 'spark_cleaning_job', 'manual__2025-04-13T04:15:14.218770+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/daily.py', '--cfg-path', '/tmp/tmpkiybj0xs']
[2025-04-13, 13:15:16 KST] {standard_task_runner.py:85} INFO - Job 70: Subtask spark_cleaning_job
[2025-04-13, 13:15:16 KST] {task_command.py:415} INFO - Running <TaskInstance: dag_spark_daily.spark_cleaning_job manual__2025-04-13T04:15:14.218770+00:00 [running]> on host 407b97dc98e0
[2025-04-13, 13:15:16 KST] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_spark_daily' AIRFLOW_CTX_TASK_ID='spark_cleaning_job' AIRFLOW_CTX_EXECUTION_DATE='2025-04-13T04:15:14.218770+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-13T04:15:14.218770+00:00'
[2025-04-13, 13:15:16 KST] {base.py:73} INFO - Using connection ID 'spark-conn' for task execution.
[2025-04-13, 13:15:16 KST] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions --conf spark.sql.catalog.spark_catalog=org.apache.iceberg.spark.SparkSessionCatalog --conf spark.sql.catalog.spark_catalog.type=hive --conf spark.sql.catalog.iceberg=org.apache.iceberg.spark.SparkCatalog --conf spark.sql.catalog.iceberg.type=hive --conf spark.sql.catalog.iceberg.uri=thrift://hive-metastore:9083 --conf spark.sql.catalog.minio=org.apache.iceberg.spark.SparkCatalog --conf spark.sql.catalog.minio.type=iceberg --conf spark.sql.catalog.minio.uri=thrift://hive-metastore:9083 --conf spark.hadoop.fs.s3a.access.key=minio --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.hadoop.fs.s3a.aws.credentials.provider=org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider --conf spark.sql.parquet.enableVectorizedReader=false --conf spark.sql.catalog.minio.warehouse=s3a://datalake/ --jars /var/jars/spark-sql-kafka-0-10_2.12-3.4.1.jar,/var/jars/kafka-clients-3.4.1.jar,/var/jars/spark-streaming-kafka-0-10_2.12-3.4.1.jar,/var/jars/commons-pool2-2.11.1.jar,/var/jars/spark-token-provider-kafka-0-10_2.12-3.4.1.jar,/var/jars/aws-java-sdk-bundle-1.12.262.jar,/var/jars/hadoop-aws-3.3.4.jar --num-executors 2 --executor-cores 2 --executor-memory 4g --driver-memory 4g --name spark_cleaning_job --class com.tadod.App --verbose --deploy-mode client /var/submit/jars/tadod-spark-1.0-jar-with-dependencies.jar YellowClean /var/cleaning/application.properties 2024-02-02 2024-02-02
[2025-04-13, 13:15:16 KST] {spark_submit.py:579} INFO - /home/***/.local/lib/python3.10/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-04-13, 13:15:16 KST] {spark_submit.py:579} INFO - JAVA_HOME is not set
[2025-04-13, 13:15:16 KST] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: 
    spark-submit 
    --master spark://spark-master:7077 
    --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions 
    --conf spark.sql.catalog.spark_catalog=org.apache.iceberg.spark.SparkSessionCatalog 
    --conf spark.sql.catalog.spark_catalog.type=hive 
    --conf spark.sql.catalog.iceberg=org.apache.iceberg.spark.SparkCatalog 
    --conf spark.sql.catalog.iceberg.type=hive 
    --conf spark.sql.catalog.iceberg.uri=thrift://hive-metastore:9083 
    --conf spark.sql.catalog.minio=org.apache.iceberg.spark.SparkCatalog 
    --conf spark.sql.catalog.minio.type=iceberg 
    --conf spark.sql.catalog.minio.uri=thrift://hive-metastore:9083 
    --conf spark.hadoop.fs.s3a.access.key=minio 
    --conf spark.hadoop.fs.s3a.secret.key=****** 
    --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 
    --conf spark.hadoop.fs.s3a.path.style.access=true 
    --conf spark.hadoop.fs.s3a.aws.credentials.provider=org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider 
    --conf spark.sql.parquet.enableVectorizedReader=false 
    --conf spark.sql.catalog.minio.warehouse=s3a://datalake/ 
    --jars /var/jars/spark-sql-kafka-0-10_2.12-3.4.1.jar,/var/jars/kafka-clients-3.4.1.jar,/var/jars/spark-streaming-kafka-0-10_2.12-3.4.1.jar,/var/jars/commons-pool2-2.11.1.jar,/var/jars/spark-token-provider-kafka-0-10_2.12-3.4.1.jar,/var/jars/aws-java-sdk-bundle-1.12.262.jar,/var/jars/hadoop-aws-3.3.4.jar 
    --num-executors 2 
    --executor-cores 2 
    --executor-memory 4g 
    --driver-memory 4g 
    --name spark_cleaning_job 
    --class com.tadod.App 
    --verbose 
    --deploy-mode client 
    /var/submit/jars/tadod-spark-1.0-jar-with-dependencies.jar 
    YellowClean 
    /var/cleaning/application.properties 2024-02-02 2024-02-02. Error code is: 1.
[2025-04-13, 13:15:16 KST] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=dag_spark_daily, task_id=spark_cleaning_job, execution_date=20250413T041514, start_date=20250413T041516, end_date=20250413T041516
[2025-04-13, 13:15:16 KST] {standard_task_runner.py:104} ERROR - Failed to execute job 70 for task spark_cleaning_job (Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions --conf spark.sql.catalog.spark_catalog=org.apache.iceberg.spark.SparkSessionCatalog --conf spark.sql.catalog.spark_catalog.type=hive --conf spark.sql.catalog.iceberg=org.apache.iceberg.spark.SparkCatalog --conf spark.sql.catalog.iceberg.type=hive --conf spark.sql.catalog.iceberg.uri=thrift://hive-metastore:9083 --conf spark.sql.catalog.minio=org.apache.iceberg.spark.SparkCatalog --conf spark.sql.catalog.minio.type=iceberg --conf spark.sql.catalog.minio.uri=thrift://hive-metastore:9083 --conf spark.hadoop.fs.s3a.access.key=minio --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.hadoop.fs.s3a.aws.credentials.provider=org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider --conf spark.sql.parquet.enableVectorizedReader=false --conf spark.sql.catalog.minio.warehouse=s3a://datalake/ --jars /var/jars/spark-sql-kafka-0-10_2.12-3.4.1.jar,/var/jars/kafka-clients-3.4.1.jar,/var/jars/spark-streaming-kafka-0-10_2.12-3.4.1.jar,/var/jars/commons-pool2-2.11.1.jar,/var/jars/spark-token-provider-kafka-0-10_2.12-3.4.1.jar,/var/jars/aws-java-sdk-bundle-1.12.262.jar,/var/jars/hadoop-aws-3.3.4.jar --num-executors 2 --executor-cores 2 --executor-memory 4g --driver-memory 4g --name spark_cleaning_job --class com.tadod.App --verbose --deploy-mode client /var/submit/jars/tadod-spark-1.0-jar-with-dependencies.jar YellowClean /var/cleaning/application.properties 2024-02-02 2024-02-02. Error code is: 1.; 870)
[2025-04-13, 13:15:16 KST] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-04-13, 13:15:16 KST] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check